/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author dcastro
 */
import controllers.Archivos;
import controllers.ChangeEvent;
import controllers.ChangeEventController;
import controllers.ChangeEventListener;
import controllers.ChangeEventListenerController;
import controllers.Controller;
import licencia.Validate;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JToolBar;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
public class Busqueda extends javax.swing.JFrame {

/**
     * Creates new form Busqueda
     */
        public Busqueda() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupOptModelo = new javax.swing.ButtonGroup();
        grupModelos = new javax.swing.JPanel();
        optDeprati = new javax.swing.JRadioButton();
        optBbp = new javax.swing.JRadioButton();
        optInternacional = new javax.swing.JRadioButton();
        opt_mupi = new javax.swing.JRadioButton();
        optBg = new javax.swing.JRadioButton();
        optCredi = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtRutaLista = new javax.swing.JTextField();
        btnListaFaltantes = new javax.swing.JButton();
        txtRutaCarpeta = new javax.swing.JTextField();
        btnCarpetaArchivos = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelBuscadas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelEncontradas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelFaltante = new javax.swing.JLabel();
        labelinfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca Faltante");

        grupModelos.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccion Modelo"));

        groupOptModelo.add(optDeprati);
        optDeprati.setText("DEPRATI");

        groupOptModelo.add(optBbp);
        optBbp.setText("BBP");

        groupOptModelo.add(optInternacional);
        optInternacional.setText("INTERNACIONAL");

        groupOptModelo.add(opt_mupi);
        opt_mupi.setText("MUPI");

        groupOptModelo.add(optBg);
        optBg.setSelected(true);
        optBg.setText("BG");

        optCredi.setText("CREDICORP");

        javax.swing.GroupLayout grupModelosLayout = new javax.swing.GroupLayout(grupModelos);
        grupModelos.setLayout(grupModelosLayout);
        grupModelosLayout.setHorizontalGroup(
            grupModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupModelosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optBg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optDeprati)
                .addGap(18, 18, 18)
                .addComponent(optBbp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optInternacional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opt_mupi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optCredi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        grupModelosLayout.setVerticalGroup(
            grupModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupModelosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grupModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optDeprati)
                    .addComponent(optBbp)
                    .addComponent(optInternacional)
                    .addComponent(opt_mupi)
                    .addComponent(optBg)
                    .addComponent(optCredi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccion Archivos"));

        btnListaFaltantes.setText("FALTANTES");
        btnListaFaltantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaFaltantesActionPerformed(evt);
            }
        });

        txtRutaCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaCarpetaActionPerformed(evt);
            }
        });

        btnCarpetaArchivos.setText("INDIVIDUALES");
        btnCarpetaArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpetaArchivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRutaLista, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(txtRutaCarpeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListaFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarpetaArchivos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListaFaltantes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarpetaArchivos))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Resultados"));

        jLabel1.setText("Buscadas:");

        labelBuscadas.setText("0");

        jLabel3.setText("Encontradas:");

        labelEncontradas.setText("0");

        jLabel5.setText("No encontradas:");

        labelFaltante.setText("0");

        labelinfo.setText("..............");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelBuscadas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelEncontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(labelFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelBuscadas)
                    .addComponent(jLabel3)
                    .addComponent(labelEncontradas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelFaltante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelinfo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(23)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(6)
        					.addComponent(btnBuscar)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(grupModelos, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(22)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(grupModelos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(12)
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
        
        JMenuBar menuBar = new JMenuBar();
        setJMenuBar(menuBar);
        
        JMenu mnNewMenu = new JMenu("Config");
        menuBar.add(mnNewMenu);
        
        JMenuItem mntmNewMenuItem = new JMenuItem("Licencia");
        mntmNewMenuItem.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//Validate val = new Validate();
        		Validate.showActivarLicencia();
        		
        	}
        });
        mnNewMenu.add(mntmNewMenuItem);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if("".equals(this.txtRutaLista.getText()) || "".equals(this.txtRutaCarpeta.getText())){
            JOptionPane.showMessageDialog(null, "Seleccione Listado y archivos","Mensaje de error",ERROR_MESSAGE);
        }else{
            ThreadCarga carga = new ThreadCarga();
            carga.start();
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListaFaltantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaFaltantesActionPerformed

        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();        
        FileFilter filtro = new FileNameExtensionFilter("Archivos Txt (.txt)", "txt"); 
        fileChooser.setFileFilter(filtro);        
        fileChooser.showOpenDialog(fileChooser);
        this.txtRutaLista.setText(fileChooser.getSelectedFile().getAbsolutePath());   
    }//GEN-LAST:event_btnListaFaltantesActionPerformed

    private void btnCarpetaArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpetaArchivosActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();        
        //FileFilter filtro = new FileNameExtensionFilter("Archivos Txt (.txt)", "txt"); 
        //fileChooser.setFileFilter(filtro);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.showOpenDialog(fileChooser);
        this.txtRutaCarpeta.setText(fileChooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_btnCarpetaArchivosActionPerformed

    private void txtRutaCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaCarpetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaCarpetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Busqueda().setVisible(true);
            }
        });*/
    }
    class ThreadCarga extends Thread {
        ChangeEventListener events = (ChangeEvent ev, String fileName) -> {
            //System.out.println("Se cambió el ID"+fileName);
            labelinfo.setText(fileName);
            //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        };
        
        ChangeEventListenerController eventsController = new ChangeEventListenerController() {
            @Override
            public void onCountBuscarChange(ChangeEventController ev, int count) {
                //System.out.println("Se cambió el ID"+ count +"");
                labelBuscadas.setText(count+"");
                labelFaltante.setText(count+"");

            }

            @Override
            public void onCountEncontradoChange(ChangeEventController ev, int count) {
                labelEncontradas.setText(count+"");
                labelFaltante.setText((Integer.parseInt(labelBuscadas.getText()) - count)+"");
            }

            @Override
            public void onMenssageChange(ChangeEventController ev, String message) {
                labelinfo.setText(message);
                
             }

            @Override
            public void onMenssageErrorChange(ChangeEventController ev, String message) {
                JOptionPane.showMessageDialog(null, "Error: "+ message,"Mensaje de error",ERROR_MESSAGE);
                System.exit(0);
                
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
            
        };
        
        @Override
        public void run() {
            String modelo="";
            if(optBg.isSelected()){modelo="bg";}
            if(optBbp.isSelected()){modelo="bbp";}
            if(optDeprati.isSelected()){modelo="adp";}
            if(optInternacional.isSelected()){modelo="intr";}
            if(opt_mupi.isSelected()){modelo="mupi";}
            if(optCredi.isSelected()){modelo="credi";}
            Archivos archivos = new Archivos(txtRutaCarpeta.getText());
            archivos.addEventListener(events);
            Controller controlador = new Controller(archivos,txtRutaLista.getText(),modelo);
            controlador.addEventListener(eventsController);
            controlador.procesar();
        }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCarpetaArchivos;
    private javax.swing.JButton btnListaFaltantes;
    private javax.swing.ButtonGroup groupOptModelo;
    private javax.swing.JPanel grupModelos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBuscadas;
    private javax.swing.JLabel labelEncontradas;
    private javax.swing.JLabel labelFaltante;
    private javax.swing.JLabel labelinfo;
    private javax.swing.JRadioButton optBbp;
    private javax.swing.JRadioButton optBg;
    private javax.swing.JRadioButton optCredi;
    private javax.swing.JRadioButton optDeprati;
    private javax.swing.JRadioButton optInternacional;
    private javax.swing.JRadioButton opt_mupi;
    private javax.swing.JTextField txtRutaCarpeta;
    private javax.swing.JTextField txtRutaLista;
}
